# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-05-10 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ext_uid',
            field=models.CharField(default='', max_length=16, unique=True, verbose_name='第三登录的唯一标识'),
        ),
    ]
