# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-05-11 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_ext_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_sex', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=8, verbose_name='匹配的性别')),
                ('dating_location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('广州', '广州'), ('深圳', '深圳')], max_length=20, verbose_name='目标城市')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最小交友年龄')),
                ('max_dating_age', models.IntegerField(default=50, verbose_name='最大交友年龄')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最小查找范围')),
                ('max_distance', models.IntegerField(default=30, verbose_name='最大查找范围')),
                ('vibration', models.BooleanField(default=True, verbose_name='是否开启震动')),
                ('only_matched', models.BooleanField(default=True, verbose_name='是否只让匹配的人看到')),
                ('auto_play', models.BooleanField(default=True, verbose_name='是否自动播放')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
