# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-05-11 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dating_location',
            field=models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('广州', '广州'), ('深圳', '深圳'), ('浙江', '浙江')], max_length=20, verbose_name='目标城市'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('广州', '广州'), ('深圳', '深圳'), ('浙江', '浙江')], max_length=20, verbose_name='常居地'),
        ),
    ]
