# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-05-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210511_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ext_uid',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='第三登录的唯一标识'),
        ),
    ]
